# swagger configuration
# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing
                                              # pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings
  # definitions (see https://github.com/apigee-127/bagpipes)
  bagpipes:
    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

server:
  port: 10010

amqp:
  url: amqp://localhost

logger:
  path: ./log
  transports:
    File:
      options:
        filename: default.log
        level: info
        json: false
        maxsize: 5242880
        maxFiles: 100
        timestamp: true
        prettyPrint: true
        colorize: true
        tailable: true
    Console:
      options:
        level: info
        json: false
        timestamp: true
        prettyPrint: true
        colorize: true

#   Template Loggly transport configuration
#
#   NOTE: Add token and subdomain to your local configuration file
#
#   Loggly:
#     require: winston-loggly
#     options:
#       level: info
#       subdomain: The subdomain of your Loggly account [required]
#       inputToken: The input token [required]
#       tags:
#         - your tags here
#         - another tag
#       json: true
#       stripColors: true

  levels:
    debug: 4
    verbose: 3
    info: 2
    warn: 1
    error: 0
  colors:
    debug: blue
    verbose: white
    info: green
    warn: yellow
    error: red
